---
title: "Anomaly_detection.rmd"
author: "Bundi Kirimi"
date: "2/5/2022"
output: html_document
---

#Anomaly Detection


```{R}
# Installing anomalize package
# ---install.packages("anomalize")
```

```{r}
#install.packages('devtools') 
devtools::install_github("business-science/anomalize")
```


```{r}
#install.packages("anomalize") #Anormally detection
library(anomalize)
library(lubridate)
library(tibbletime)
```





```{R}
# Collect our time series data
# ---
# 
tidyverse_cran_downloads
```






```{r}
#Loading the data
path <-"http://bit.ly/CarreFourSalesDataset" 

df1<-read.csv(path, sep = ",")

head(df1)
```



```{R}
# Verifying the object's class
# ---
# This should show us transactions as the type of data that we will need
# ---
# 
class(df1)
```




```{r}
str(df1)

```
```{r}
summary(df1)
```



Using the ‘anomalize’ package
The R ‘anomalize’ package enables a workflow for detecting anomalies in data. The main functions are time_decompose(), anomalize(), and time_recompose().


`

```{r}

library(tidyverse)

# Detecting our anomalies
# ----
# We now use the following functions to detect and visualize anomalies; 
# We decomposed the “count” column into “observed”, “season”, “trend”, and “remainder” columns. 
# The default values for time series decompose are method = "stl", 
# which is just seasonal decomposition using a Loess smoother (refer to stats::stl()). 
# The frequency and trend parameters are automatically set based on the time scale (or periodicity)
# of the time series using tibbletime based function under the hood.
# time_decompose() - this function would help with time series decomposition.
# 
# anomalize() - 
# We perform anomaly detection on the decomposed data using 
# the remainder column through the use of the anomalize() function 
# which procides 3 new columns; “remainder_l1” (lower limit), 
# “remainder_l2” (upper limit), and “anomaly” (Yes/No Flag).
# The default method is method = "iqr", which is fast and relatively 
# accurate at detecting anomalies. 
# The alpha parameter is by default set to alpha = 0.05, 
# but can be adjusted to increase or decrease the height of the anomaly bands, 
# making it more difficult or less difficult for data to be anomalous. 
# The max_anoms parameter is by default set to a maximum of max_anoms = 0.2 
# for 20% of data that can be anomalous. 
# 
# time_recompose()-
# We create the lower and upper bounds around the “observed” values 
# through the use of the time_recompose() function, which recomposes 
# the lower and upper bounds of the anomalies around the observed values.
# We create new columns created: “recomposed_l1” (lower limit) 
# and “recomposed_l2” (upper limit).
# 
# plot_anomalies() - 
# we now plot using plot_anomaly_decomposition() to visualize out data.
# 
# ---
# 
tidyverse_cran_downloads %>%
    time_decompose(count) %>%
    anomalize(remainder) %>%
    time_recompose() %>%
    plot_anomalies(time_recomposed = TRUE, ncol = 3, alpha_dots = 0.5)
```


