---
title: "Association_Analysis.rmd"
author: "Bundi Kirimi"
date: "2/5/2022"
output: html_document
---

http://bit.ly/SupermarketDatasetII



```{R}
# We first we install the required arules library 
#install.packages("arules")
```


```{R}
# Loading the arules library
#
library(arules)
```





#Loading the data
```{r}


path <-"http://bit.ly/SupermarketDatasetII"

df<-read.transactions(path, sep = ",")
df
```

```{r}

```



#Previewing the summary of the dataset
```{r}
summary(df)
```

#Checking the data
```{r}
#Length
length(df)
```
The dataframe has 18 columns


````{r}
#Dimensions
dim(df)

````




#The dataframe has 12330 row entries and 18 columns
Column Names
```{r}
colnames(df)

```
```{R}
# Verifying the object's class
# ---
# This should show us transactions as the type of data that we will need
# ---
# 
class(df)
```

```{r}
any(is.na(df))
```



```{R}
# Previewing our first 5 transactions
#
inspect(df[1:5])
```


```{R}
# If we wanted to preview the items that make up our dataset,
# alternatively we can do the following
# ---
# 
items<-as.data.frame(itemLabels(df))
colnames(items) <- "Item"
head(items, 10)    
```

```{R}
# Generating a summary of the transaction dataset
# ---
# This would give us some information such as the most purchased items, 
# distribution of the item sets (no. of items purchased in each transaction), etc.
# ---
# 
summary(df)
```


```{R}
# Exploring the frequency of some articles 
# i.e. transacations ranging from 8 to 10 and performing 
# some operation in percentage terms of the total transactions 
# 
itemFrequency(df[, 8:10],type = "absolute")
round(itemFrequency(df[, 8:10],type = "relative")*100,2)
```

```{r}
# Producing a chart of frequencies and fitering 
# to consider only items with a minimum percentage 
# of support/ considering a top x of items
# ---
# Displaying top 10 most common items in the transactions dataset 
# and the items whose relative importance is at least 10%
# 
par(mfrow = c(1, 2))

# plot the frequency of items
itemFrequencyPlot(df, topN = 10,col="darkgreen")
itemFrequencyPlot(df, support = 0.1,col="darkred")

```

```{R}
# Building a model based on association rules 
# using the apriori function 
# ---
# We use Min Support as 0.001 and confidence as 0.8
# ---
# 
rules <- apriori (df, parameter = list(supp = 0.001, conf = 0.8))
rules

```


```{R}
# We use measures of significance and interest on the rules, 
# determining which ones are interesting and which to discard.
# ---
# However since we built the model using 0.001 Min support 
# and confidence as 0.8 we obtained 410 rules.
# However, in order to illustrate the sensitivity of the model to these two parameters, 
# we will see what happens if we increase the support or lower the confidence level
# 

# Building a apriori model with Min Support as 0.002 and confidence as 0.8.
rules2 <- apriori (df,parameter = list(supp = 0.002, conf = 0.8)) 

# Building apriori model with Min Support as 0.002 and confidence as 0.6.
rules3 <- apriori (df, parameter = list(supp = 0.001, conf = 0.6)) 

rules2

rules3
```

```{R}
# We can perform an exploration of our model 
# through the use of the summary function as shown
# ---
# Upon running the code, the function would give us information about the model 
# i.e. the size of rules, depending on the items that contain these rules. 
# In our above case, most rules have 3 and 4 items though some rules do have upto 6. 
# More statistical information such as support, lift and confidence is also provided.
# ---
# 
summary(rules)
```


```{R}
# Observing rules built in our model i.e. first 5 model rules
# ---
# 
inspect(rules[1:5])


# Interpretation of the first rule:
# ---
# If someone buys liquor and red/blush wine, they are 90% likely to buy bottled beer too
# ---
```


```{R}
# Ordering these rules by a criteria such as the level of confidence
# then looking at the first five rules.
# We can also use different criteria such as: (by = "lift" or by = "support")
# 
rules<-sort(rules, by="confidence", decreasing=TRUE)
inspect(rules[1:5])

# Interpretation
# ---
# The given five rules have a confidence of 100
# ---
```


```{R}
# We can perform an exploration of our model 
# through the use of the summary function as shown
# ---
# Upon running the code, the function would give us information about the model 
# i.e. the size of rules, depending on the items that contain these rules. 
# In our above case, most rules have 3 and 4 items though some rules do have upto 6. 
# More statistical information such as support, lift and confidence is also provided.
# ---
# 
summary(rules)
```


```{R}
# Observing rules built in our model i.e. first 5 model rules
# ---
# 
inspect(rules[1:5])


# Interpretation of the first rule:
# ---
# If someone buys liquor and red/blush wine, they are 90% likely to buy bottled beer too
# ---
```
